name: Empty Action
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  do_something:
    runs-on: ubuntu-latest
  steps:
    - name: empty step
      run: echo DONE
